#!/bin/bash -l

#SBATCH --nodes 3
#SBATCH --ntasks-per-node 2
#SBATCH --cpus-per-task 1
#SBATCH --mem 32000
#SBATCH --time 00:10:00

#SBATCH --mail-type=ALL
#SBATCH --account=pppcc2016
#SBATCH --mail-user=guillaume.leclerc@epfl.ch

module purge
module load mvapich2/2.0.1/gcc-4.4.7
module load gcc/4.8.3

echo "3 - 2 - 1"
/usr/bin/time -f "%e" sh -c "srun /home/gpolecle/final/main 100000000 1 > /dev/null"
