#!/bin/bash -l

#SBATCH --nodes __N__
#SBATCH --ntasks-per-node __TPN__
#SBATCH --cpus-per-task 1
#SBATCH --mem 32000
#SBATCH --time 00:10:00

#SBATCH --mail-type=ALL
#SBATCH --account=pppcc2016
#SBATCH --mail-user=guillaume.leclerc@epfl.ch

module purge
module load mvapich2/2.0.1/gcc-4.4.7
module load gcc/4.8.3

echo "__N__ - __TPN__ - __R__"
/usr/bin/time -f "%e" sh -c "srun /home/gpolecle/final/main 100000000 __R__ > /dev/null"
